### ISSUE TITLE
Install R add-on packages on GNURoot Fedora

### ISSUE THREAD

**Issue by wbhuangxm** [corbinlc/gnuroot#1]
yum install R
yum install gcc\* (install all compiler)
yum install make ( update make)

but when install add-on package using install.packages() in R environment or using R CMD INSTALL in Fedora, I persistently encountered following error

collect2: fatal error: cannot find 'ld', 
compilation terminated

**Comment by liuqun** [comment]
ld is part of binutils package.
 Try: yum install gcc binutils

**Comment by liuqun** [comment]
![screenshot_2014-02-27-14-57-47](https://f.cloud.github.com/assets/64795/2279931/a563be8c-9f7c-11e3-854c-6445a483adab.png)

PS:
I am using gnuroot Aboriginal right now. gcc and ld have been installed already.

**Comment by corbinlc** [comment]
Can you update this issue?  The app has improved significantly since then and I have had many users report that they are running R if wheezy or fedora.  Also, can you updated it based on the suggestions given to install more packages?
