### ISSUE TITLE
On wheezy, df and mount do not work, symlink of /etc/mtab fixes it

### ISSUE THREAD

**Issue by zoobab** [corbinlc/gnuroot#11]
On wheezy, df and mount does not work.

Just replace /etc/mtab with a symlink:

$ ln -s /proc/mounts /etc/mtab

And then df and mount works fine.

I don't know how to fix it in the tar.gz.

**Comment by corbinlc** [comment]
Does this work without rooting your device?  I haven't tried it yet.  I can patch people's installs and modify this in future .tar.gz files.  That is easy to do.  I am on a hiatus from development, but will be solving many issues fairly soon.

**Comment by cedric-vincent** [comment]
@corbinlc: without patching installs, you can add "-b /proc/mounts:/etc/mtab" to the list of options passed to PRoot.

**Comment by corbinlc** [comment]
@cedric-vincent so true.  That is easier.  Thanks!

**Comment by corbinlc** [comment]
@zoobab can you tell me if your device was rooted, because mount doesn't work on my test device even with this change?  Also, can you tell me exactly what you ran from the command line and how it behaved before and after this change?  Thanks!

**Comment by corbinlc** [comment]
I just pushed a new version of GNURoot to the store (give it a couple of hours to show up).  It makes it so you don't have to make the symbolic link.  Typing mount or df properly prints the mounts present on your device now.  @zoobab, still interested in what you specifically wanted to do?

**Comment by zoobab** [comment]
will check if it fixes the issue...

**Comment by tonigi** [comment]
On my unrooted nexus 7, df works fine on wheezy (mount of course not).
