### ISSUE TITLE
executing commands not permitted

### ISSUE THREAD

**Issue by ghost** [corbinlc/gnuroot#18]
Hi!
I'd love to use GNUroot. However, on a fresh wheezy rootfs i cannot execute commands like ls, it keeps telling me operation not permitted. ls works when I type /bin/ls <dir>. Also the apt-get command can't be found. What am i doing wrong? 
Thanks for any help!

**Comment by corbinlc** [comment]
1)  Do you see any warning or error messages in the terminal when you launch?
2) What do you see if you do this:?           /bin/ls  -l  /
3) What do you see as the value of the PATH environment variable?

**Comment by ghost** [comment]
At launch a warning appears: 
bash: dircolors: command not found. $PATH is 
/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin
I've tried adding :/bin to the path but on export $PATH I get an error 'not a valid identifier'
'/bin/ls -l /' lists the root folder of my internal storage, also listing a bin directory that i can't see with a file browser. Ownerships for the folders are root root or 1000 1000 for most of the folders listed. 

Do you need a more verbose output? Thanks for your reply! 

<div>-------- Original message --------</div><div>From: corbinlc notifications@github.com </div><div>Date:18/07/2014  23:26  (GMT+01:00) </div><div>To: corbinlc/gnuroot gnuroot@noreply.github.com </div><div>Cc: Schubisu Robin.Schubert@gmx.de </div><div>Subject: Re: [gnuroot] executing commands not permitted (#18) </div><div>
</div>1) Do you see any warning or error messages in the terminal when you launch?
2) What do you see if you do this:? /bin/ls -l /
3) What do you see as the value of the PATH environment variable?

**Comment by psema4** [comment]
This works for me:

```
export PATH="/bin:${PATH}"
```

but otherwise seeing the same with wheezy & wheezyx on Galaxy Note 8

Edit:
Looks like /usr/bin needs to be added to the path as well. Change above to:

```
export PATH="/bin:/usr/bin:${PATH}"
```

apt-get works for me after that

**Comment by psema4** [comment]
above export should be expanded to:

```
export PATH="/bin:/usr/bin:/usr/sbin:${PATH}"
```

Still have some broken stuff but here's a rough [quickstart gist](https://gist.github.com/psema4/c1545694272b1939b429)
