### ISSUE TITLE
where should I put the *.obb files?

### ISSUE THREAD

**Issue by zuyih** [corbinlc/gnuroot#31]
When I press "Create New Rootfs", It saids "Download failed because the resources could not be found', So I directly download the .obb file from dropbox, Where should I put the *.obb files in. Thank You.

**Comment by dinosauria123** [comment]
Put .obb file at
/mnt/shell/emulated/obb/champion.gnuroot.wheezy/  (if you use wheezy)

**Comment by zuyih** [comment]
Thank you very much.
