### ISSUE TITLE
Overwrite Android with GnuRoot???

### ISSUE THREAD

**Issue by OzOle** [corbinlc/gnuroot#32]
I have a quad-core unit. Is there any way I can remove the Android OS and instead install a Linux OS, e.g. Wheezy with a light weight gui?

I would like to dedicate all the resources of my unit 100% to Linux. I am aware that if I press the restore button then I will reinstall Android and overwrite the Linux OS I have installed, so that must be avoided if I don't want to start all over again.

Thank you so much for the great work you are doing with this!

Kind regards,

Ole

**Comment by corbinlc** [comment]
I am sorry, but this really isn't in the scope of this project.  I have heard there are ways to dual boot a phone so it runs android and a standard linux distro, but haven't tried it myself.  Regardless, I don't think GNURoot will help you with this.
