### ISSUE TITLE
SSH in Wheezy doesn't work, neither OpenSSH server, nor Dropbear, /dev/pts issues

### ISSUE THREAD

**Issue by dmayle** [corbinlc/gnuroot#40]
I've tried the latest version of the apks, downloaded from your test directory mentioned in other issues, but it still doesn't work.

**Comment by tonigi** [comment]
I have this issue since upgrading to android L. Looks like /dev is unaccessible to non-root in this version.

**Comment by dmayle** [comment]
I forgot to mention that.  Yes, I'm using Android L as well

**Comment by tonigi** [comment]
Perhaps /dev/ptmx and/or related library calls can be emulated in user space?

**Comment by corbinlc** [comment]
I can confirm this issue.  I don't have a suggested solution yet.  I see there are some SSH apps working for Android L, so there must be a way.  Will need to research this.

**Comment by norcimo5** [comment]
Same issue on Galaxy Note 4

**Comment by jpweiss** [comment]
This is not just an Android L. issue.
I have GNURoot installed on a tablet running 4.4.2, and all of the `/dev/pty*` files can only be accessed by root.  I've seen this from the Wheezy and Wheezyx installs.

**Comment by HappyAmos** [comment]
Gnu root on Galaxy S4 running Ki5Kat 4.4.2, same issue, any progress on this?

**Comment by skylerparr** [comment]
Having the same issue on Android L. Debian wheezy x86.

**Comment by januxnet** [comment]
Same issue on newer Android (Marshmallow 6.0.1 - Galaxy S7 Edge)

**Comment by dmayle** [comment]
Issue is stale, closing
