### ISSUE TITLE
Small files take up much space

### ISSUE THREAD

**Issue by gphilip** [corbinlc/gnuroot#46]
Firstly, thank you for this great software.

I ran across this issue while trying to use offlineimap in GnuRoot Wheezy. The installation went fine, but trying to transfer my existing mail corpus  over to a GnuRoot (i) took way too much time to complete, and (ii) resulted in way too much of the (external) sdcard being used up. Investigating a bit, I found that (at least) the latter was due to the huge number of small files (4.0K or less) that offlineimap creates to do its thing. 

So the issue is: each small file (of size, say, a few kilobytes) created on GnuRoot Wheezy takes up 128K of space. This is a showstopper for my use case, since my 7GB email archive blows up to a few tens of GB when extracted on GnuRoot, thereby exhausting my external sdcard. 

I made the following test case to illustrate this:

---
## Test Case
1. Create a single file of ~200 KB (Can use /dev/zero if /dev/random is not available or is slow):
   
   $ dd if=/dev/random of=master.file bs=1 count=200000
    ....
   $ du -h master.file
   256K    master.file
2. Split this file into umpteen pieces, each of size a hundred bytes:
   
   $ split -b 100 -a 4 master.file
   
   (This could take some time.. .)
3. Check the space used up by the collection of split files:
   
   $ du -chs x*
   128K    xaaaa
   128K    xaaab
       ....
       ....
   128K   xacyx
   250M  total
   ---
   ## End Test Case

Is there a workaround? Am I doing things wrong somehow, causing small files to take up much space?

Thank you!

**Comment by cedric-vincent** [comment]
Hello @gphilip,

On Tue, Feb 03, 2015 at 01:18:56AM -0800, gphilip wrote:

> Test Case
> 
> ```
> 1. Create a single file of ~200 KB (Can use /dev/zero if /dev/random
>    is not available or is slow):
>    $ dd if=/dev/random of=master.file bs=1 count=200000
>    ....
>    $ du -h master.file
>    256K master.file
> 2. Split this file into umpteen pieces, each of size a hundred bytes:
>    $ split -b 100 -a 4 master.file
>    (This could take some time.. .)
> 3. Check the space used up by the collection of split files:
>    $ du -chs x*
>    128K xaaaa
>    128K xaaab
>    ....
>    ....
>    128K xacyx
>    250M total
>      ______________________________________________________________
> 
>    End Test Case
> ```
> 
>    Is there a workaround? Am I doing things wrong somehow, causing small
>    files to take up much space?

Maybe your sdcard was formatted to use 128KB clusters/blocks (no files
can't be smaller than that).

**Comment by corbinlc** [comment]
@gphilip have you formatted your sdcard in a specific way?  Mine is formatted with 4kB cluster size.  I have not chosen that.  It maybe universally the default for android devices, or it might be just this device/manufactures default.

**Comment by gphilip** [comment]
Hi @cedric-vincent and @corbinlc ,

  Sorry for the late response, I was travelling and didn't get a chance to take this up before now.

  It looks like my sdcard is formatted to use 128KB blocks, as you suggested. I repeated the above test using Terminal IDE (https://play.google.com/store/apps/details?id=com.spartacusrex.spartacuside&hl=en) twice, once on my internal sdcard and then on my external sdcard. On the internal sdcard all the xa\* file sizes were 4K each, and on the external sdcard they were 128K each. This seems to confirm your conjecture, so I am closing this issue.
