### ISSUE TITLE
"am" gives Segmentation fault

### ISSUE THREAD

**Issue by mayureshw** [corbinlc/gnuroot#63]
Trying to run /system/bin/am.

/system/bin/am works fine on Terminal IDE application. So borrowed entire environment (incl BOOTCLASSPATH, LD_LIBRARY_PATH, PATH and actually everything else) from a terminal IDE session, exported before launching am.

Still get a segmentation fault.

Are android native binaries not supposed to work?

**Comment by jasonspiro** [comment]
Which version of GNURoot are you running (e.g. Wheezy or WheezyX), and which version number?

You can get the version number from Settings > Application Manager.

**Comment by jasonspiro** [comment]
Also:  IIRC, `am` is Android's "activity manager".  Correct?

**Comment by mayureshw** [comment]
am is a program (I don't know for sure about it being acronym) I use to launch native android programs.  (E.g I manage PDF store using my Linux software and vi, but to view a PDF I need and prefer a native PDF viewer of android, which I can launch using am.) Augmenting Linux based programs this way to use native software where necessary makes a Linux layer on android all the more powerful.

The issue is not with "am" alone. I can't launch any binary in /system/bin (which I can in the Terminal IDE app).

I am using WheezyX 0.0.2 (I deleted the app after creating rootfs as I am running short on space. So finding the version from playstore. BTW I think extsd installation for rootfs is not supported, which seems a critical requirement for many users.)

**Comment by corbinlc** [comment]
This is the same as https://github.com/corbinlc/gnuroot/issues/7 .  This is a limitation of PRoot.  I have  a planned future work around that will allow something specifically like "am" to work from within GNURoot Debian.  GNURoot Debian will be able to receive intents from other apps (already working, but going to improve soon).  GNURoot Debian will be fire intents to other apps (one specific example working for GNURoot Octave, but a more generic solution coming).

**Comment by mayureshw** [comment]
Thanks. Closing as it is duplicate of #7
