### ISSUE TITLE
Iceweasel does not work in Gnuroot

### ISSUE THREAD

**Issue by jfrandol** [corbinlc/gnuroot#72]
edit: I guess I should say this is GNuRoot debian:

with the default install, after I install iceweasel with apt-get update, apt-get install iceweasel, then when I run iceweasel, It errors with Your Iceweasel profile cannot be loaded. It may be missing or inaccessible. -  there is an error related to glib shown in the console that may or may not be related:

 "GLib-CRITICAL **: g_slice_set_config: assertion `sys_page_size == 0' failed" 

Let me know if you need more information and I can try to provide  (RCA 10 Viking tablet with lolipop 5.0)

It is probably an upstream problem ? - but would anyone be able to point me in a direction of how to fix it? - do you think there is an alternate iceweasel binary or glib binary I could use ?

Regards,

John F

**Comment by lucamaggioni** [comment]
Hi

Same problem here.

I've installed gnuroot and iceweasel, but problems arises:

Gdk-WARNING **: shmget failed: error 13 (Permission denied)

Any news?

Thanks
Luca

**Comment by lucamaggioni** [comment]
... Same use case but not the same problem... so I've opened issue #79: https://github.com/corbinlc/gnuroot/issues/79

**Comment by jfrandol** [comment]
I tried this again recently in Gnuroot Debian, and it seems fixed  (just did the upgrade in the UI)
Thank you.
