### ISSUE TITLE
Rootfs location in Android file system

### ISSUE THREAD

**Issue by Atulin** [corbinlc/gnuroot#89]
A simple question, really: I have Wheezyx installed, and I need to access its root location. I'm using it to run R, and all the charts, session data and such are being saved there. I'd like to backup those. 

My phone is rooted, so there's no problem accessing system files if need be.

**Comment by Atemu** [comment]
/data/data/champion.gnuroot/app_install/roots/

**Comment by Atulin** [comment]
Yep, it's there. Thanks!
